FROM node:22-slim AS base

# Instala openssl para o Prisma funcionar em imagens slim
RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copia arquivos de configuração do monorepo
COPY package.json package-lock.json ./
COPY packages/ ./packages/
COPY apps/api/package.json ./apps/api/

# Instala dependências
RUN npm install

# Copia o código do back e gera o prisma client
COPY apps/api/ ./apps/api/
RUN npm run prisma:generate -w apps/api
RUN npm run build -w apps/api

EXPOSE 3333

CMD ["npm", "run", "start", "-w", "apps/api"]
